version: '3'
services:

  btc-app:
      build:
        context: .
        dockerfile: ./DockerfileApi
      restart: always
      ports:
        - "8002:8000" 
      environment:
      - SERVICE_PORT=8000
      - DB_NAME=BCT_TEST
      - DB_USER=root
      - DB_PASSWORD=bananapi
      - DB_HOST=10.0.0.33
      - DB_PORT=27017
